[project]
sourceRoot   = "ai-golf-coach-mvp"
packageManager = "yarn"

[phases.install]
command = "yarn install --frozen-lockfile"

[phases.build]
command = "yarn build"

[phases.start]
command = "yarn start"
