[project]
sourceRoot = "ai-golf-coach-mvp"
packageManager = "yarn"

[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
command = "cd ai-golf-coach-mvp && yarn install --frozen-lockfile"

[phases.build]
command = "cd ai-golf-coach-mvp && yarn build"

[phases.start]
command = "cd ai-golf-coach-mvp && yarn start"
