[project]
# relative path to the folder with your package.json + server.js
sourceRoot = "ai-golf-coach-mvp"
packageManager = "yarn"        # or "npm" if you prefer

[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
# installs dependencies inside that folder
command = "yarn install --frozen-lockfile"

[phases.build]
# runs the build script from that folder's package.json
command = "yarn build"

[start]
# runs the start script (which should point at your server.js)
command = "node server.js"

[variables]
NODE_ENV = "production"
PORT = "3000"