[project]
# override autodetect; force npm
packageManager = "npm"

[phases.install]
# use clean npm install
command = "npm ci"

[phases.build]
# build your React app
command = "npm run build"

[phases.start]
# run your server
command = "npm start"