[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
command = "yarn install --frozen-lockfile"

[phases.build]
command = "yarn build"

[start]
command = "node server.js"

[variables]
NODE_ENV = "production"
PORT = "3000" 