[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run railway-start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 